spring.application.name=schedule
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/schedule_bd
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

spring.sql.init.mode=never

# Модуль импорта: лимиты загрузки файлов (Excel/CSV нагрузки)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# Jackson: ???????????? ?????? ???? (Hibernate proxy)
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false

